#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Overall title for pages.
title: "Unix course – Introduction to basic Unix commands"

# Life cycle stage of the lesson
# See this page for more details: https://cdh.carpentries.org/the-lesson-life-cycle.html
# Possible values: "pre-alpha", "alpha", "beta", "stable"
life_cycle: "pre-alpha"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

github_username: deNBI
email: contact@denbi.de

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Sites.
training_site: "https://github.com/deNBI/unix-course"
denbi_github: "https://github.com/deNBI"
denbi_site: "https://www.denbi.de/about"
denbi_cloud_site: "https://www.denbi.de/cloud"
dekcd_site: "https://datenkompetenz.cloud/"
citation: ""
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Turn on built-in syntax highlighting.
highlighter: rouge